#!/bin/sh

# url: http://help.github.com/articles/changing-author-info

# git filter-branch --env-filter '
# an="$GIT_AUTHOR_NAME"
# am="$GIT_AUTHOR_EMAIL"
# cn="$GIT_COMMITTER_NAME"
# cm="$GIT_COMMITTER_EMAIL"

# if [ "$GIT_COMMITTER_EMAIL" = "your@email.to.match" ]
# then
#     cn="Your New Committer Name"
#     cm="Your New Committer Email"
# fi

# if [ "$GIT_AUTHOR_EMAIL" = "your@email.to.match" ]
# then
#     an="Your New Author Name"
#     am="Your New Author Email"
# fi

# export GIT_AUTHOR_NAME="$an"
# export GIT_AUTHOR_EMAIL="$am"
# export GIT_COMMITTER_NAME="$cn"
# export GIT_COMMITTER_EMAIL="$cm"
# '
run() {
    # your@email.to.match
    old_email=$1
    new_email=$2
    new_name=$3

    export old_email new_email new_name

    git filter-branch --env-filter '
an="$GIT_AUTHOR_NAME"
am="$GIT_AUTHOR_EMAIL"
cn="$GIT_COMMITTER_NAME"
cm="$GIT_COMMITTER_EMAIL"

if [ "$GIT_COMMITTER_EMAIL" = "$old_email" ]
then
echo changed >> /tmp/a
    cn="$new_name"
    cm="$new_email"
fi

if [ "$GIT_AUTHOR_EMAIL" = "$old_email" ]
then
    an="$new_name"
    am="$new_email"
fi

export GIT_AUTHOR_NAME="$an"
export GIT_AUTHOR_EMAIL="$am"
export GIT_COMMITTER_NAME="$cn"
export GIT_COMMITTER_EMAIL="$cm"
'
}

if [ $# -eq 3 ]
then
    run $*
else
    echo usage: $0 old_email new_email new_name
fi
